name: Run Test on JVMs

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Shell Script
        run: |
          chmod +x test_jvms.sh
          ./test_jvms.sh
